branches:
  only:
  - master
language: python
cache: yarn
python:
  - "3.5"
# command to install dependencies
install:
  - pip install fandogh-cli --upgrade
# command to run tests
script:
  - echo $TRAVIS_COMMIT
  - fandogh login --username=$FANDOGH_USERNAME --password=$FANDOGH_PASSWORD
  - fandogh image publish --version=$TRAVIS_COMMIT || travis_terminate 1
  - fandogh service deploy --version=$TRAVIS_COMMIT --name=start || travis_terminate 1